# Generated by Django 5.1 on 2024-12-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0002_purchase_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill_date',
            field=models.DateField(db_index=True),
        ),
    ]
