# Generated by Django 5.1 on 2024-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0002_customuser_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='driver_name',
        ),
    ]
