# Generated by Django 5.1 on 2024-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0003_rename_name_driver_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
