# Generated by Django 5.1 on 2024-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0003_alter_purchase_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
