# Generated by Django 5.1 on 2024-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_purchaseitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='adhaar_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='Driver Adhaar'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license_photo',
            field=models.FileField(blank=True, null=True, upload_to='Driving License '),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Profile Photo'),
        ),
        migrations.AddField(
            model_name='technician',
            name='adhaar_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='Driver Adhaar'),
        ),
        migrations.AddField(
            model_name='technician',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='Other Documents '),
        ),
        migrations.AddField(
            model_name='technician',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Profile Photo'),
        ),
    ]
