# Generated by Django 5.1 on 2024-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_alter_driver_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100, verbose_name='Technician Name')),
                ('adhaar_number', models.CharField(max_length=20, unique=True, verbose_name='Aadhaar Number')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
            },
        ),
    ]
