# Generated by Django 5.1 on 2024-12-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_workhshop',
            new_name='is_workshop',
        ),
    ]
