# Generated by Django 5.1 on 2024-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_driver_adhaar_card_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='adhaar_card_photo',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='other_document',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='driver',
            name='adhaar_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='Adhaar'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_photo',
            field=models.FileField(blank=True, null=True, upload_to='License '),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Photo'),
        ),
    ]
