# Generated by Django 5.1 on 2024-12-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0008_model_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ERP_Admin.model'),
        ),
    ]
